[default_config]
version = "0.10.1"
assembler = "ca65"
instruction_set = "6502"

[default_config.opts]
compiler = "ca65"
compile_flags_txt = [
    "--cpu",
    "W65C02",
]
diagnostics = true
default_diagnostics = false
